# Generated by Django 4.2.3 on 2023-09-01 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertime',
            name='bath_type',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
