# Generated by Django 4.2.3 on 2023-09-02 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0002_usertime_bath_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='num_people',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_people', models.JSONField()),
            ],
        ),
        migrations.RemoveField(
            model_name='usertime',
            name='name',
        ),
    ]
